### ISSUE TITLE
STORY: prepare prototype presentation

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#15]
As a client I want to have a presentation of the clickable product prototype so that I get an impression about the design, the webpage structure and the goal of the whole project.

**Acceptance Criteria:**
- there is a clickable prototype
- everyone knows the vision and could talk about our project
- we have got a name that reflects our vision
- we have a speaker

**Subtask:**
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/13
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/14

**Comment by ali-260011** [comment]
story estimation: 3

**Comment by wkrl** [comment]
Reguläre Gruppentermine Freitags

Vorstellung und Abgabe Prototyp

Prototyp des zukünftigen Produkts aus Anwendersicht mit groben Skizzen oder Screens (Mockups) oder sonstigen kreativen Ideen. 

- [ ] Dokumentation in Form einer Abgabe des aktuellen Projektstandes anhand "Snapshot" mit Board/Backlog/Sprintplan, mit textueller Beschreibung / Überblick (ca 2 Seiten + Bilder + URLs)  

- [ ] Projektbeschreibung

- [ ] Thema, Nutzen, Kurzbeschreibung

- [x] Arbeitsaufteilung/Teamrollen jedes Teammitglied (z.B. Frontend, Backend, UI, Product Owner, Orga, ..).

- [ ] aktueller Projektstand/Entwurf (Screens/Mockups/Backlog/Ist/Plan)

- [x] geplante Tools / Technologien / Frameworks für die Entwicklung

- [x] Grobe Architektur / grober Plan

- [ ] Mögliche Herausforderungen / Risiken

- [x] Links zu Online-Resourcen, Backlog/Git (bitte auf Funktionsfähigkeit prüfen)

nicht notwendig: lauffähiges Produkt bzw. Software.

- [ ] Abgabe als formatierte / strukturierte Datei, zB Text, PDF, Markdown, Google Doc, Wiki mit verlinkten URLs und Bildern.

Template für github/jira/trello:

https://gitlab.beuth-hochschule.de/hmenzel/playground/-/tree/feature/%2314-create-issue-template-for-prototype/templates/prototype_delivery

**Comment by kat-hi** [comment]
@alle Beteiligten. ich kann übernehmen:
- grobe Architektur (draw.io skizze)
- mögliche herausforderungen/risiken
- geplante Tools, Technologien, Framework
- Arbeitsaufteilung

ergänzen oder ändern kann ja jeder noch dann, aber würde da erstmal was hinschreiben dafür.
googledocs vorschlag von @dismaien fand ich gut! :)

**Comment by dismaien** [comment]
Dann würde ich mich an der Projektbeschreibung versuchen und die Links einsetzen. 
Damit hätten wir dann aber eigentlich schon fast alles abgedeckt oder? Vielleicht kümmert sich noch jemand um eine schöne Formatierung (wobei das wahrscheinlich eher nebenher läuft) und ein weiterer spricht/stellt vor?

**Comment by kat-hi** [comment]
Ja, Herausforderungen sind auch individuell. hätte erstmal allgemeine Punkte, da kann sicher jeder noch draufschauen und geplante Tools/Frameworks auch

**Comment by kat-hi** [comment]
und Arbeitsteilung finde ich schwierig. siehe Dokument dann. können wir gern in Slack diskutieren wie wirs schreiben

**Comment by kat-hi** [comment]
https://docs.google.com/document/d/1zOeQ6HhnPeXU8g7SbyZjWjO3hv8HRdipBq_e42bynoc/edit?usp=sharing
