### ISSUE TITLE
STORY: Create landing page and navigation (5p)

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#18]
As a (webpage-) user I want to be introduced into the webpage with a catchy landing page that includes a navigation so that I know instantly what this application is about.

**Acceptance Criteria:**
- [x] there is a landing page implemented in vuejs
- [x] there is a basic navigation idea implemented

**Subtasks:**
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/16
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/17

**Comment by ali-260011** [comment]
story estimation: 5
