### ISSUE TITLE
EPIC [COVID-19]: display datatable with COVID19 data for berlin districts

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#24]
As a client I want to have an initial working webapplication that shows covid19-data in a datatable. The datatable should show the number of recoverd covid-19 patients, the number of new cases and the number of deaths within a week per berlin-district so that I can sort the table per column

**Acceptance Criteria:**
- [x] number of recovered covid19 patients, number of new cases and number of deaths within a week is fetched
- [x] data is stored in db
- [x] db-service can read data from db
- [x] webserver can fetch data from db-service
- [x] webpage displays a datatable of recovered COVID19 patients. 

**Subtasks:**
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/19
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/22
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/23
