### ISSUE TITLE
EPIC [TEXT]: small changes to text fields for uniform design (8p)

### ISSUE THREAD

**Issue by wkrl** [Api-visualizer/api-visualizer-FE#247]
As a user I want to be able to receive information from the web app as quick as possible. To me, this requires a uniform text layout. 

Acceptance criteria:
Text fields are uniform no matter what view a user is visiting.

Tasks: 
- [x] text align justify on every card
- [x] close function for map text info box
- [x] remove "Rows per page:" from covid pred table
- [x] add 2nd paragraph to covid pred text box
- [x] title & subtitle for every map text box component (like /infections)
- [x] title and subtitle for every non-map view
- [x] contact font smaller, like faq
- [x] fix links in menu
- [x] adapt menu-points and mainpoints in landingpage (use submenu COVID19> prediction, infection etc)
