### ISSUE TITLE
EPIC[CSS/JS]: small css changes (13p)

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#252]
As a user I want to receive information from the visualizations as quick as possible to analyze trends faster. A uniform composing of text fields and sections is required to make this happen.

Acceptance criteria:
All view's sections or fields have uniform styling, margin / padding.

- [x] adapt hamburger margin - same margins top and right
- [x]  show searchbar in landing page
- [x] screenshot for predictions in landingpage
- [x] adapt footer in every view (should be equal)
- [x] covid graph, FAQ with landing-page svg background
- [x] cancer selection should be placed on top of chart (left)
- [x] center landing page logo
- [x] adapt labels in prediction: show only first and last date<
- [x] shadow - reduce opacity, smaller and less smooth
- [x] covid-infection: reduce width of selection, centralize timeslider and maybe move zoom a bit up
- [x] covid-infection: use a fix width for card data info box
- [x] in every view: leaflet-legends and info-text box should get same top and corner margin  
- [x] in hospital-view: move zoom to bottomright
- [x] accident-view: move zoom to bottomright
- [x] faq header differs on landing page and faq page
