### ISSUE TITLE
STORY: heatmap with timeslider

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#29]
As a (webapp-)user I want to have a look at a heatmap of berlin and use a timeslide, so that I can explore the changes of the number of covid19 cases in berlin per district.

**Acceptance Criteria**
- [ ] Frontend displays a map of berlin
- [ ] Frontend displays a timeslider
- [ ] moving the slide will change heatmap values

**Subtasks:**
- [ ] https://github.com/Api-visualizer/api-visualizer-FE/issues/25
- [ ] https://github.com/Api-visualizer/api-visualizer-FE/issues/26
- [ ] https://github.com/Api-visualizer/api-visualizer-FE/issues/27
- [ ] https://github.com/Api-visualizer/api-visualizer-FE/issues/28

**Comment by wkrl** [comment]
this seems to describe https://github.com/Api-visualizer/api-visualizer-FE/issues/34 now. heatmaps only make sense when we have more data points that differ from their coordinates.
