### ISSUE TITLE
STORY [COVID-Berlin]: map displaying covid19 data per district on a given day (p21)

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#34]
As a (webapp-)user I want to have a visualization about the number of covid19 patients of each district in berlin on a given day so that I can compare the districts.

Description
The purpose of this story is to start with a simple example and to improve UX with another story by adding a timeslider.

**Acceptance Criteria:**
- [x] view for berlin component
- [x] view for berlin > corona component
- [x] there is a map displaying geo shapes for berlin's districts with covid data
- [x] the data is requested from our DB

**Subtask**

- https://github.com/Api-visualizer/api-visualizer-FE/issues/30
- https://github.com/Api-visualizer/api-visualizer-FE/issues/31
- https://github.com/Api-visualizer/api-visualizer-FE/issues/32
- https://github.com/Api-visualizer/api-visualizer-FE/issues/42

**Comment by ali-260011** [comment]
story estimation: 55
