### ISSUE TITLE
EPIC [ACCIDENTS]: display traffic accidents depending on kind as heatmap

### ISSUE THREAD

**Issue by wkrl** [Api-visualizer/api-visualizer-FE#40]
As a user i want to discover traffic accidents on a map. I want to select between [Fußgänger, Fahrrad, Auto, Krafträder, LKW]. I want to click on an accident point and see more information like time and date. 

Acceptance Criteria:

- [x] points are clickable and display more data based on the accident
- [x] frontend has check boxes that change the accident type and update the map accordingly

Subtask:
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/97
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/124
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/125
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/126

**Comment by NikRup** [comment]
https://unfallatlas.statistikportal.de/
