### ISSUE TITLE
EPIC [WALKS]: walking routes through berlin

### ISSUE THREAD

**Issue by wkrl** [Api-visualizer/api-visualizer-FE#41]
As a user I want to see walking routes to get inspired or walk them myself and see where I am going.

Berlin.de provided data for this.

Acceptance Criteria:

- [ ] data fetch https://www.berlin.de/sen/uvk/en/nature-and-green/landscape-planning/20-green-walks-in-berlin/digital-map-of-walks/
- [ ] service returning all routes in db on request
- [ ] selection to select route (by name)
- [ ] route on map
- [ ] routes clickable and displaying info in middle of route (see feature properties)
- [ ] user's live location on map

**Comment by wkrl** [comment]
Closing this, doesn't work with the current project vision anymore. :sob:
