### ISSUE TITLE
STORY [COVID-Berlin]: finish map setup (p13)

### ISSUE THREAD

**Issue by wkrl** [Api-visualizer/api-visualizer-FE#50]
As a user I want to explore the covid map by selecting a specific date. I also want to view more about the data that's being displayed so I can get a better understanding. 

**Acceptance Criteria:**
We have a representable and bullet proof map. 

**Subtasks:**
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/51
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/53
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/52
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/54
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/55
- [x] (add text for detail view, styling)
