### ISSUE TITLE
STORY: Extend Covid Map (8p)

### ISSUE THREAD

**Issue by pthrrr** [Api-visualizer/api-visualizer-FE#62]
As a user I want to quickly distinguish information of the covid spread per district. when I hover over a district I want so see all data instantly. for a quick overview I would prefer different color shades of the districts.

Acceptance criteria:
There's a covid map with distinguishable district data.

**Subtasks:**
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/63
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/67
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/68

https://leafletjs.com/examples/choropleth/
