### ISSUE TITLE
#8 STORY: Create Project Prototype (5p)

### ISSUE THREAD

**Issue by kat-hi** [Api-visualizer/api-visualizer-FE#8]
As a client, I want a clickable project prototype that shows a basic design idea so that I get an impression how the product will look like.

**Acceptance Criteria:**
there is a clickable prototype of the project that includes:
- 3-4 example views with
- types of visualizations we want to use (heatmaps, charts, colored geografical lines/areas)

**Subtasks:**
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/9
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/10
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/11
- [ ] https://github.com/Api-visualizer/api-visualizer-FE/issues/12

**Comment by ali-260011** [comment]
story estimation: 5
