### ISSUE TITLE
EPIC [WEBSITE]: improvements/fixes for the frontend

### ISSUE THREAD

**Issue by pthrrr** [Api-visualizer/api-visualizer-FE#87]
- this epic should be updated for every new sprint

- the goal is to improve the look and feel of the website and to fix bugs

- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/86
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/102
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/118
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/117
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/157
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/147
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/179
- improve mail 
- [x] https://github.com/Api-visualizer/api-visualizer-FE/issues/227
